project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Stefan Krysa"
  date: "03/28/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd

bibliography: references.bi

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual